OUTPUT=prototracker-opll

$(OUTPUT): $(CPP_SRC) $(CPP_H) $(C_OBJ)
	g++ -O3 -Wformat -std=c++11 -o $@ $(CPP_SRC) $(C_OBJ) -lSDL2_image -lSDL2main `sdl2-config --cflags --libs` -s
	
$(C_OBJ): $(C_SRC) $(C_H)
	gcc -c -o $@ $(C_SRC) -O3 -Wall -std=gnu99
